# Generated by Django 5.2.1 on 2025-06-02 08:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_accesstoken'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='integrationapplication',
            options={'verbose_name': 'Integratsiya dasturi', 'verbose_name_plural': 'Integratsiya dasturlari'},
        ),
        migrations.AddField(
            model_name='integrationapplication',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='integrationapplication',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='integrationapplication',
            name='client_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='integrationapplication',
            name='client_secret',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
