# Generated by Django 5.2.1 on 2025-06-02 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_integrationapplication_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='integrationapplication',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='integrationapplication',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
