# Generated by Django 5.2.1 on 2025-06-02 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_applicationlog'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ApplicationLog',
        ),
    ]
